### ISSUE TITLE
Update GitHub Actions to replace `::set-output`

### ISSUE THREAD

**Issue by PortableProgrammer** [PortableProgrammer/Status-Light#83]
Per the [11 October 2022 GitHub Blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), `::set-output` is deprecated and should be replaced.

In [docker-image.yml](https://github.com/PortableProgrammer/Status-Light/blob/9e4fcb9cefcef8d7b21997702e3d665ef53f0318/.github/workflows/docker-image.yml#L35-L41), switch to `$GITHUB_ENV`:

```yaml
# Example actions
-
  name: Prepare
  id: prepare
  run: |
    echo "docker_image=${DOCKER_IMAGE}" >> "$GITHUB_ENV"
    echo "version=${VERSION}" >> "$GITHUB_ENV"

- 
  name: Docker Check Manifest
  run: |
    docker run --rm mplatform/mquery ${{ env.docker_image }}:${{ env.version }}
```
